import React, { useEffect, useState } from 'react';
import { Activity, ArrowDown, ArrowUp, Bot, Plus, Trash2, X } from 'lucide-react';

type Candidate={id:string;provider_key:string;model_id:string;priority:number;enabled:number;health_state:string};
type Profile={id:string;profile_key:string;name:string;max_attempts:number;max_cost_usd:number;candidates:Candidate[]};
type Agent={key:string;label:string;profile:string;metrics:{calls:number;cost_usd:number;successes:number}};

export function AgentsModal({isOpen,onClose}:{isOpen:boolean;onClose:()=>void}){
  const [agents,setAgents]=useState<Agent[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[providerKey,setProviderKey]=useState('omniroute'),[modelId,setModelId]=useState('auto'),[profileKey,setProfileKey]=useState('BASE_FREE'),[error,setError]=useState(''),[engineEnabled,setEngineEnabled]=useState<boolean|null>(null);
  const load=async()=>{const [a,p,v]=await Promise.all([fetch('/api/agents').then(r=>r.json()),fetch('/api/model-profiles').then(r=>r.json()),fetch('/api/version').then(r=>r.json())]);setAgents(a.agents||[]);setProfiles(p.profiles||[]);setEngineEnabled(Boolean(v.agentEngineEnabled))};
  useEffect(()=>{if(isOpen)load().catch(()=>setError('Não foi possível carregar agentes e perfis.'))},[isOpen]);
  const mutate=async(url:string,method:string,body?:unknown)=>{setError('');const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Operação falhou.');setProfiles(data.profiles||[])};
  if(!isOpen)return null;
  return <div className="fixed inset-0 z-50 bg-slate-950/75 backdrop-blur-sm flex items-center justify-center p-5"><div className="w-full max-w-5xl max-h-[88vh] overflow-auto rounded-2xl border border-slate-700/80 bg-slate-950 shadow-2xl">
    <header className="sticky top-0 z-10 flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/95 backdrop-blur"><div><h2 className="text-lg font-semibold text-white flex items-center gap-2"><Bot size={19} className="text-cyan-400"/>Agentes e roteamento</h2><p className="text-xs text-slate-400 mt-1">Papéis fixos, modelos substituíveis, custo e saúde observáveis.</p></div><button onClick={onClose} className="p-2 text-slate-400 hover:text-white"><X size={18}/></button></header>
    <div className="p-6 space-y-7">
      {engineEnabled===false&&<section className="rounded-xl border border-amber-800/60 bg-amber-950/30 px-4 py-3 text-xs text-amber-200">O Agent Engine está configurado, mas desativado neste runtime. Os perfis podem ser preparados aqui sem executar orquestração multiagente até <span className="font-mono">AGENT_ENGINE_ENABLED=true</span>.</section>}
      {engineEnabled===true&&<section className="rounded-xl border border-emerald-800/60 bg-emerald-950/25 px-4 py-3 text-xs text-emerald-200">Agent Engine ativo neste runtime. Roteamento por perfil, telemetria e limites de custo estão habilitados.</section>}
      <section><h3 className="text-xs uppercase tracking-wider text-slate-500 mb-3">Equipe do MVP</h3><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{agents.map(a=><div key={a.key} className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="font-semibold text-slate-100">{a.key}</div><div className="text-[11px] text-slate-400 mt-1">{a.label}</div><div className="mt-3 text-[10px] text-cyan-300">{a.profile}</div><div className="text-[10px] text-slate-500 mt-1">{a.metrics.calls} chamadas · ${Number(a.metrics.cost_usd).toFixed(3)}</div></div>)}</div></section>
      <section><div className="flex items-center gap-2 mb-3"><Activity size={15} className="text-emerald-400"/><h3 className="text-sm font-semibold text-slate-100">Perfis de modelo</h3></div><div className="grid lg:grid-cols-3 gap-3">{profiles.map(p=><div key={p.id} className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex justify-between"><div><div className="font-semibold text-slate-100">{p.name}</div><div className="text-[10px] font-mono text-slate-500">{p.profile_key}</div></div><div className="text-[10px] text-slate-400">até ${p.max_cost_usd}</div></div><div className="mt-3 space-y-2">{p.candidates.map((c,i)=><div key={c.id} className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-950 p-2"><button onClick={()=>mutate(`/api/model-candidates/${c.id}`,'PATCH',{priority:Math.max(0,c.priority-1)}).catch(e=>setError(e.message))} title="Subir"><ArrowUp size={12}/></button><button onClick={()=>mutate(`/api/model-candidates/${c.id}`,'PATCH',{priority:c.priority+1}).catch(e=>setError(e.message))} title="Descer"><ArrowDown size={12}/></button><div className="min-w-0 flex-1"><div className="truncate text-[11px] text-slate-200">{c.provider_key} · {c.model_id}</div><div className="text-[9px] text-slate-500">#{i+1} · {c.health_state}</div></div><button onClick={()=>mutate(`/api/model-candidates/${c.id}`,'PATCH',{enabled:!c.enabled}).catch(e=>setError(e.message))} className={`text-[9px] px-1.5 py-1 rounded ${c.enabled?'text-emerald-300 bg-emerald-950':'text-slate-400 bg-slate-800'}`}>{c.enabled?'ativo':'pausado'}</button><button onClick={()=>mutate(`/api/model-candidates/${c.id}`,'DELETE').catch(e=>setError(e.message))}><Trash2 size={12} className="text-rose-400"/></button></div>)}</div></div>)}</div></section>
      <section className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><h3 className="text-sm font-semibold text-slate-100 mb-3 flex items-center gap-2"><Plus size={14}/>Adicionar modelo ao perfil</h3><div className="grid sm:grid-cols-4 gap-2"><select value={profileKey} onChange={e=>setProfileKey(e.target.value)} className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs">{profiles.map(p=><option key={p.id} value={p.profile_key}>{p.name}</option>)}</select><input value={providerKey} onChange={e=>setProviderKey(e.target.value)} placeholder="provedor" className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs"/><input value={modelId} onChange={e=>setModelId(e.target.value)} placeholder="modelo" className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs"/><button onClick={()=>mutate(`/api/model-profiles/${profileKey}/candidates`,'PUT',{providerKey,modelId,priority:99}).catch(e=>setError(e.message))} className="rounded-lg bg-cyan-500 text-slate-950 text-xs font-semibold">Adicionar</button></div>{error&&<p className="mt-3 text-xs text-rose-300">{error}</p>}</section>
    </div></div></div>
}

